[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
daddy_inu = "4JTpmcGZjrTeS6QzQBzjsG3B4t1kEbR2JD9uspnhARdP"

[rpc]
url = "http://127.0.0.1:8899"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "/home/lyonkvalid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
